#!/bin/sh
set -eo pipefail

__WARNING_LINE_1="DO NOT MODIFY"
__WARNING_LINE_2="Generated by /docker-entrypoint-scripts/generate-nginx-lua-modules/env-vars-available.lua.sh"

__ENV_VAR_NAMES="$(env | sed -e 's/=.*//')"

# Write the Lua env loading file
printf "----\n--  ${__WARNING_LINE_1}\n--  ${__WARNING_LINE_2}\n----\n\n" \
  > ${NGINX__ENV__LUA_FILE_PATH}
printf "local _M = {}\n\n" \
 >> ${NGINX__ENV__LUA_FILE_PATH}
printf "${__ENV_VAR_NAMES}" \
  | sed -e "s/^\(.*\)$/_M[\"\1\"] = os.getenv(\"\1\")/" \
 >> ${NGINX__ENV__LUA_FILE_PATH}
printf "\n\nreturn _M\n" \
 >> ${NGINX__ENV__LUA_FILE_PATH}
