#!/bin/sh
set -eo pipefail

__WARNING_LINE_1="DO NOT MODIFY"
__WARNING_LINE_2="Generated by /docker-entrypoint.sh"

__NGINX_ENV_CONF_FILE_PATH=$NGINX__PREFIX/conf/env_vars_available.conf
__NGINX_ENV_LUA_FILE_PATH=$OPENRESTY__PREFIX/lualib/generated/env_vars_available.lua

__ENV_VAR_NAMES="$(env | sed -e 's/=.*//')"

# Write the NGINX env config file
printf "####\n##  ${__WARNING_LINE_1}\n##  ${__WARNING_LINE_2}\n####\n\n" \
  > ${__NGINX_ENV_CONF_FILE_PATH}
printf "${__ENV_VAR_NAMES}" \
  | sed -e "s/^\(.*\)$/env \1;/" \
 >> ${__NGINX_ENV_CONF_FILE_PATH}
printf "\n" \
 >> ${__NGINX_ENV_CONF_FILE_PATH}

# Write the Lua env loading file
printf "----\n--  ${__WARNING_LINE_1}\n--  ${__WARNING_LINE_2}\n----\n\n" \
  > ${__NGINX_ENV_LUA_FILE_PATH}
printf "local _M = {}\n\n" \
 >> ${__NGINX_ENV_LUA_FILE_PATH}
printf "${__ENV_VAR_NAMES}" \
  | sed -e "s/^\(.*\)$/_M[\"\1\"] = os.getenv(\"\1\")/" \
 >> ${__NGINX_ENV_LUA_FILE_PATH}
printf "\n\nreturn _M\n" \
 >> ${__NGINX_ENV_LUA_FILE_PATH}

# Create the caching directories if they do not already exist
if [ ! -d "$NGINX__HTTP__PROXY__TEMP_PATH" ]; then
    mkdir "$NGINX__HTTP__PROXY__TEMP_PATH"
fi
if [ ! -d "$NGINX__HTTP__CLIENT_BODY__TEMP_PATH" ]; then
    mkdir "$NGINX__HTTP__CLIENT_BODY__TEMP_PATH"
fi
if [ ! -d "$NGINX__FCGI__PROXY__TEMP_PATH" ]; then
    mkdir "$NGINX__FCGI__PROXY__TEMP_PATH"
fi

exec "$@"
