#!/bin/sh
set -eo pipefail

__WARNING_LINE_1="DO NOT MODIFY"
__WARNING_LINE_2="Generated by /docker-entrypoint-scripts/generate-nginx-conf-includes/access-log.conf.sh"

printf "####\n##  ${__WARNING_LINE_1}\n##  ${__WARNING_LINE_2}\n####\n\n" \
  > ${NGINX__HTTP__LOG_CONFIG__ACCESS__CONF_FILE_PATH}
printf "access_log  ${NGINX__HTTP__LOG_CONFIG__ACCESS};\n" \
  >> ${NGINX__HTTP__LOG_CONFIG__ACCESS__CONF_FILE_PATH}
