#!/bin/sh
set -e

__WARNING_LINE_1="DO NOT MODIFY"
__WARNING_LINE_2="Generated by /docker-entrypoint-scripts/generate-nginx-conf-includes/brotli_window.conf.sh"

printf "%b" "####\n##  ${__WARNING_LINE_1}\n##  ${__WARNING_LINE_2}\n####\n\n" \
  > ${NGINX__BROTLI_WINDOW__CONF_FILE_PATH}
printf "%b" "brotli_window  ${NGINX__BROTLI_WINDOW};\n" \
  >> ${NGINX__BROTLI_WINDOW__CONF_FILE_PATH}
