#!/bin/sh
set -e

__WARNING_LINE_1="DO NOT MODIFY"
__WARNING_LINE_2="Generated by /docker-entrypoint-scripts/generate-nginx-conf-includes/env.conf.sh"

__ENV_VAR_NAMES="$(env | sed -e 's/=.*//')"

printf "%b" "####\n##  ${__WARNING_LINE_1}\n##  ${__WARNING_LINE_2}\n####\n\n" \
  > ${NGINX__ENV__CONF_FILE_PATH}
printf "%b" "${__ENV_VAR_NAMES}" \
  | sed -e "s/^\(.*\)$/env \1;/" \
 >> ${NGINX__ENV__CONF_FILE_PATH}
printf "%b" "\n" \
 >> ${NGINX__ENV__CONF_FILE_PATH}
