#!/bin/sh
set -eo pipefail

__WARNING_LINE_1="DO NOT MODIFY"
__WARNING_LINE_2="Generated by /docker-entrypoint-scripts/generate-nginx-conf-includes/error-log.conf.sh"

printf "####\n##  ${__WARNING_LINE_1}\n##  ${__WARNING_LINE_2}\n####\n\n" \
  > ${NGINX__ERROR_LOG__CONF_FILE_PATH}
printf "error_log  /dev/stderr  ${NGINX__ERROR_LOG_LEVEL};\n" \
  >> ${NGINX__ERROR_LOG__CONF_FILE_PATH}
