#!/bin/sh
set -e

__WARNING_LINE_1="DO NOT MODIFY"
__WARNING_LINE_2="Generated by /docker-entrypoint-scripts/generate-nginx-conf-includes/gzip_types.conf.sh"

printf "%b" "####\n##  ${__WARNING_LINE_1}\n##  ${__WARNING_LINE_2}\n####\n\n" \
  > ${NGINX__GZIP_TYPES__CONF_FILE_PATH}
printf "%b" "gzip_types  ${NGINX__COMPRESSION_TYPES};\n" \
  >> ${NGINX__GZIP_TYPES__CONF_FILE_PATH}
