#!/bin/sh
set -eo pipefail

__WARNING_LINE_1="DO NOT MODIFY"
__WARNING_LINE_2="Generated by /docker-entrypoint-scripts/generate-nginx-conf-includes/keepalive-timeout.conf.sh"

printf "####\n##  ${__WARNING_LINE_1}\n##  ${__WARNING_LINE_2}\n####\n\n" \
  > ${NGINX__KEEPALIVE_TIMEOUT__CONF_FILE_PATH}
printf "keepalive_timeout  ${NGINX__KEEPALIVE_TIMEOUT};\n" \
  >> ${NGINX__KEEPALIVE_TIMEOUT__CONF_FILE_PATH}
